export const COMPANIES = 'COMPANIES';
export const COMPANIES_PAGE_LIMIT = 'COMPANIES_PAGE_LIMIT';
export const CREATE_COMPANY = 'CREATE_COMPANY';
export const SET_UPDATED_COMPANY = 'SET_UPDATED_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';
