export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_REGISTRATION_TOKEN = 'SET_REGISTRATION_TOKEN';
export const REMOVE_REGISTRATION_TOKEN = 'REMOVE_REGISTRATION_TOKEN';

export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const UPDATE_TOKENS = 'UPDATE_TOKENS';

export const COMPANIES = 'COMPANIES';
export const COMPANIES_PAGE_LIMIT = 'COMPANIES_PAGE_LIMIT';
export const CREATE_COMPANY = 'CREATE_COMPANY';
export const SET_UPDATED_COMPANY = 'SET_UPDATED_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const CLEAN_UPDATED_COMPANY = 'CLEAN_UPDATED_COMPANY';

export const WAREHOUSES = 'WAREHOUSES';
export const WAREHOUSES_NAMES = 'WAREHOUSES_NAMES';
export const WAREHOUSES_PAGE_LIMIT = 'WAREHOUSES_PAGE_LIMIT';
export const CREATE_WAREHOUSE = 'CREATE_WAREHOUSE';
export const SET_UPDATED_WAREHOUSE = 'SET_UPDATED_WAREHOUSE';
export const UPDATE_WAREHOUSE = 'UPDATE_WAREHOUSE';
export const DELETE_WAREHOUSE = 'DELETE_WAREHOUSE';
export const CLEAN_UPDATED_WAREHOUSE = 'CLEAN_UPDATED_WAREHOUSE';

export const USERS = 'USERS';
export const USERS_PAGE_LIMIT = 'USERS_PAGE_LIMIT';
export const CREATE_USER = 'CREATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const SET_UPDATED_USER = 'SET_UPDATED_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const CLEAN_UPDATED_USER = 'CLEAN_UPDATED_USER';

export const CARRIERS = 'CARRIERS';
export const CARRIERS_NAMES = 'CARRIERS_NAMES';
export const CARRIERS_PAGE_LIMIT = 'CARRIERS_PAGE_LIMIT';
export const CREATE_CARRIER = 'CREATE_CARRIER';
export const DELETE_CARRIER = 'DELETE_CARRIER';
export const SET_UPDATED_CARRIER = 'SET_UPDATED_CARRIER';
export const UPDATE_CARRIER = 'UPDATE_CARRIER';
export const CLEAN_UPDATED_CARRIER = 'CLEAN_UPDATED_CARRIER';

export const DRIVERS = 'DRIVERS';
export const DRIVERS_NAMES = 'DRIVERS_NAMES';
export const DRIVERS_PAGE_LIMIT = 'DRIVERS_PAGE_LIMIT';
export const CREATE_DRIVER = 'CREATE_DRIVER';
export const DELETE_DRIVER = 'DELETE_DRIVER';
export const SET_UPDATED_DRIVER = 'SET_UPDATED_DRIVER';
export const UPDATE_DRIVER = 'UPDATE_DRIVER';
export const CLEAN_UPDATED_DRIVER = 'CLEAN_UPDATED_DRIVER';
export const CLEAN_DRIVERS = 'CLEAN_DRIVERS';
export const CLEAN_DRIVERS_NAMES = 'CLEAN_DRIVERS_NAMES';

export const STORAGES = 'STORAGES';
export const STORAGES_PAGE_LIMIT = 'STORAGES_PAGE_LIMIT';
export const CREATE_STORAGE = 'CREATE_STORAGE';
export const SET_UPDATED_STORAGE = 'SET_UPDATED_STORAGE';
export const UPDATE_STORAGE = 'UPDATE_STORAGE';
export const DELETE_STORAGE = 'DELETE_STORAGE';
export const STORAGE_TYPES = 'STORAGE_TYPES';
export const CLEAN_UPDATED_STORAGE = 'CLEAN_UPDATED_STORAGE';

export const SENDERS = 'SENDERS';
export const SENDERS_NAMES = 'SENDERS_NAMES';
export const SENDERS_PAGE_LIMIT = 'SENDERS_PAGE_LIMIT';
export const CREATE_SENDER = 'CREATE_SENDER';
export const SET_UPDATED_SENDER = 'SET_UPDATED_SENDER';
export const UPDATE_SENDER = 'UPDATE_SENDER';
export const DELETE_SENDER = 'DELETE_SENDER';
export const CLEAN_UPDATED_SENDER = 'CLEAN_UPDATED_SENDER';

export const RECEIVERS = 'RECEIVERS';
export const RECEIVERS_PAGE_LIMIT = 'RECEIVERS_PAGE_LIMIT';
export const CREATE_RECEIVER = 'CREATE_RECEIVER';
export const SET_UPDATED_RECEIVER = 'SET_UPDATED_RECEIVER';
export const UPDATE_RECEIVER = 'UPDATE_RECEIVER';
export const DELETE_RECEIVER = 'DELETE_RECEIVER';
export const CLEAN_UPDATED_RECEIVER = 'CLEAN_UPDATED_RECEIVER';

export const TRANSPORT = 'TRANSPORT';
export const TRANSPORT_NAMES = 'TRANSPORT_NAMES';
export const TRANSPORT_PAGE_LIMIT = 'TRANSPORT_PAGE_LIMIT';
export const CREATE_TRANSPORT = 'CREATE_TRANSPORT';
export const SET_UPDATED_TRANSPORT = 'SET_UPDATED_TRANSPORT';
export const UPDATE_TRANSPORT = 'UPDATE_TRANSPORT';
export const DELETE_TRANSPORT = 'DELETE_TRANSPORT';
export const CLEAN_UPDATED_TRANSPORT = 'CLEAN_UPDATED_TRANSPORT';
export const CLEAN_TRANSPORT = 'CLEAN_TRANSPORT';
export const CLEAN_TRANSPORT_NAMES = 'CLEAN_TRANSPORT_NAMES';

export const TTN = 'TTN';
export const CREATE_TTN = 'CREATE_TTN';
export const TTN_PAGE_LIMIT = 'TTN_PAGE_LIMIT';
export const SET_UPDATED_TTN = 'SET_UPDATED_TTN';
export const DELETE_TTN = 'DELETE_TTN';
export const CLEAN_UPDATED_TTN = 'CLEAN_UPDATED_TTN';
export const USER_INFO = 'USER_INFO';

export const GOODS = 'GOODS';
export const GOODS_ITEM_INIT = 'GOODS_ITEM_INIT';
export const GOODS_ITEM_COMPUTED_VOLUME = 'GOODS_ITEM_COMPUTED_VOLUME';
export const SET_STORAGE_CURRENT_CAPACITY = 'SET_STORAGE_CURRENT_CAPACITY';
export const STORAGE_CURRENT_CAPACITY = 'STORAGE_CURRENT_CAPACITY';
export const CREATE_WRITE_OFF = 'CREATE_WRITE_OFF';

export const SET_TOAST = 'SET_TOAST';

export const REQUEST = 'REQUEST';
export const SUCCESS = 'SUCCESS';
