export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_REGISTRATION_TOKEN = 'SET_REGISTRATION_TOKEN';
export const REMOVE_REGISTRATION_TOKEN = 'REMOVE_REGISTRATION_TOKEN';

export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const UPDATE_TOKENS = 'UPDATE_TOKENS';

export const COMPANIES = 'COMPANIES';
export const COMPANIES_PAGE_LIMIT = 'COMPANIES_PAGE_LIMIT';
export const CREATE_COMPANY = 'CREATE_COMPANY';
export const SET_UPDATED_COMPANY = 'SET_UPDATED_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const CURRENT_COMPANY = 'CURRENT_COMPANY';

export const WAREHOUSES = 'WAREHOUSES';
export const WAREHOUSES_PAGE_LIMIT = 'WAREHOUSES_PAGE_LIMIT';
export const CREATE_WAREHOUSE = 'CREATE_WAREHOUSE';
export const SET_UPDATED_WAREHOUSE = 'SET_UPDATED_WAREHOUSE';
export const UPDATE_WAREHOUSE = 'UPDATE_WAREHOUSE';
export const DELETE_WAREHOUSE = 'DELETE_WAREHOUSE';
export const CURRENT_WAREHOUSE = 'CURRENT_WAREHOUSE';

export const USERS = 'USERS';
export const USERS_PAGE_LIMIT = 'USERS_PAGE_LIMIT';
export const CREATE_USER = 'CREATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const SET_UPDATED_USER = 'SET_UPDATED_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const STORAGES = 'STORAGES';
export const STORAGES_PAGE_LIMIT = 'STORAGES_PAGE_LIMIT';
export const CREATE_STORAGE = 'CREATE_STORAGE';
export const SET_UPDATED_STORAGE = 'SET_UPDATED_STORAGE';
export const UPDATE_STORAGE = 'UPDATE_STORAGE';
export const DELETE_STORAGE = 'DELETE_STORAGE';

export const SENDERS = 'SENDERS';
export const SENDERS_PAGE_LIMIT = 'SENDERS_PAGE_LIMIT';
export const CREATE_SENDER = 'CREATE_SENDER';
export const SET_UPDATED_SENDER = 'SET_UPDATED_SENDER';
export const UPDATE_SENDER = 'UPDATE_SENDER';
export const DELETE_SENDER = 'DELETE_SENDER';

export const SET_TOAST = 'SET_TOAST';
