export const SYSTEM_ADMIN_ROLE = 'System Admin';
export const COMPANY_ADMIN_ROLE = 'Company Admin';
export const WAREHOUSE_DISPATCHER_ROLE = 'Warehouse Dispatcher';
export const WAREHOUSE_CONTROLLER_ROLE = 'Warehouse Controller';
export const WAREHOUSE_MANAGER_ROLE = 'Warehouse Manager';

export const ROLES = [SYSTEM_ADMIN_ROLE, COMPANY_ADMIN_ROLE,
  WAREHOUSE_CONTROLLER_ROLE, WAREHOUSE_DISPATCHER_ROLE, WAREHOUSE_MANAGER_ROLE
];
export const ROLES_FOR_CREATING = [SYSTEM_ADMIN_ROLE];
export const ROLES_FOR_CREATING_COMPANY_USERS = [COMPANY_ADMIN_ROLE, WAREHOUSE_DISPATCHER_ROLE, WAREHOUSE_CONTROLLER_ROLE, WAREHOUSE_MANAGER_ROLE];

export const WAREHOUSE_ROLES = [WAREHOUSE_DISPATCHER_ROLE, WAREHOUSE_CONTROLLER_ROLE, WAREHOUSE_MANAGER_ROLE];
